# Generated by Django 5.2.1 on 2025-05-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurent",
            name="restaurent_type",
            field=models.CharField(
                choices=[
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("IT", "Italian"),
                    ("GR", "Greek"),
                    ("MX", "Mexican"),
                    ("FF", "Fast Food"),
                    ("OT", "Others"),
                ],
                default="",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
