# Generated by Django 5.2.1 on 2025-05-29 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="restaurent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="core.restaurent",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="restaurent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="core.restaurent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "restaurent")},
        ),
    ]
