# Generated by Django 5.2.1 on 2025-06-04 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurent",
            name="latitute",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="restaurent",
            name="longitute",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="income",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
