# Generated by Django 5.2.1 on 2025-06-06 04:43

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_restaurent_latitute_alter_restaurent_longitute_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurent",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
    ]
